### ISSUE TITLE
Please "git tag" your RAKU modules with it's versions

### ISSUE THREAD

**Issue by AntonOks** [2colours/raku-File-Temp#2]
Can you please "GIT TAG" your RAKU modules with it's version, similar and at the same time you maintain it's **_"version": "x.y.z"_** in your `META6.json` file?
I was told, this will happen "for free" going forward with mi6 anyhow, but for now it would be great if you spend those 2 seconds already now :)

"Tagging" is generally highly appreciated in regards to "reproducible builds" and here especially for the ["Rakudo Star" modules](https://github.com/rakudo/star/blob/master/etc/modules.txt)

THANK YOU!

**Comment by AntonOks** [comment]
@rbt  ping...

**Comment by AntonOks** [comment]
@rbt seems like you lost interest?! if so, would you mind if this repo would be transferred to https://github.com/raku-community-modules ?

**Comment by rbt** [comment]
Sure. I'd be happy to transfer the repo. Can you provide some directions on how to go about doing that?

Transfer owner gives me this:

"You don’t have the permission to create public repositories on raku-community-modules"

**Comment by 2colours** [comment]
Perhaps different rules apply to individual users and organizations?

@rbt by the way, if it's fine by you, you could transfer it to me as well. It's kind of a thankless state to be a community module, waiting for adoption. I already picked up a couple of modules.

**Comment by AntonOks** [comment]
> Sure. I'd be happy to transfer the repo. Can you provide some directions on how to go about doing that?
> 
> Transfer owner gives me this:
> 
> "You don’t have the permission to create public repositories on raku-community-modules"

I have no idea how this "community-modules" thing is meant to work. If you are willing to transfer, I could ask in the "raku-dev" channel :|

**Comment by 2colours** [comment]
@AntonOks So... will this do? ^^
